apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: infnet-guia
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'infnet-guia'
        metrics_path: '/api/metrics'
        scrape_interval: 10s
        static_configs:
          - targets: ['infnet-guia-service:80']
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            replacement: 'infnet-guia'
